spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_database?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        batch_size: 1000
        show_sql: true
  batch:
    jdbc:
      initialize-schema: always

file:
  excel-path: /Users/ibang/Desktop/test.xlsx